dist: bionic
sudo: required
language:
  - cpp
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    packages:
      - libsdl2-dev
      - cmake

env:
  global:
    - LANG="en_US.UTF-8"
    - CTEST_EXT_COLOR_OUTPUT=TRUE
    - CTEST_BUILD_FLAGS=-j4

before_script:
  - mkdir build
  - cd build

script:
  - cmake ..
  - make
  - ctest -VV .