dist: bionic
sudo: required
language:
  - cpp
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    packages:
      - libsdl2-dev
      - cmake
	  - ctest
before_script:
  - mkdir build
script:
  - cmake ..
  - make
  - ctest -j4
env:
  global:
    - LANG="en_US.UTF-8"