dist: bionic
sudo: required
language:
  - cpp
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    packages:
      - libsdl2-dev
	  - cmake
script:
  - mkdir build && cd build && cmake --build .. && ./bin/CosmicExplorer --exit
env:
  global:
    - LANG="en_US.UTF-8"