dist: bionic
sudo: required
language:
  - cpp
compiler:
  - gcc
os:
  - linux
addons:
  apt:
    packages:
      - libsdl2-dev
      - cmake
script:
  - mkdir build && cd build && cmake .. && make && make install && cd bin && ./tests
env:
  global:
    - LANG="en_US.UTF-8"