language: cpp
compiler:
- gcc
os:
- linux
before_install:
- echo $LANG
- echo $LC_ALL
- if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install libsdl2-dev; fi
script:
- if [ $TRAVIS_OS_NAME == linux ]; then make; fi

env:
  global:
  - LANG="en_US.UTF-8"