name: CMake CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - name: install dependencies
      run: sudo apt install libsdl2-dev
      
    - name: generate makefile
      run: mkdir build && cd build && cmake ..
      
    - name: make
      run: cd build && make
     
    - name: make test
      run: cd build && make test ARGS=-j4
