name: CMake CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout from master
      uses: actions/checkout@master
    
    - name: install dependencies
      run: sudo apt install libsdl2-dev
      
    - name: generate makefile
      run: mkdir build && cd build && cmake ..
      
    - name: make
      run: cd build && make
     
    - name: make test
      run: cd build && make test ARGS=-j4

  build_emscripten_release:
    runs-on: ubuntu-latest
    steps:
    - name: checkout from master
      uses: action/checkout@master
    
    - name: setup emcripten
      uses: mymindstorm/setup-emsdk@v1
    
    - name: generate makefile
      run: mkdir release && cd release && emconfigure cmake -DCMAKE_BUILD_TYPE=Release ..
    
    - name: make
      run: cd release && make
     
    - name: deploy to github pages
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/bin
